var searchData=
[
  ['aspnet',['AspNet',['../namespace_x_labs_1_1_serialization_1_1_asp_net.html',1,'XLabs::Serialization']]],
  ['autofac',['Autofac',['../namespace_x_labs_1_1_ioc_1_1_autofac.html',1,'XLabs::Ioc']]],
  ['behaviors',['Behaviors',['../namespace_x_labs_1_1_forms_1_1_behaviors.html',1,'XLabs::Forms']]],
  ['caching',['Caching',['../namespace_x_labs_1_1_caching.html',1,'XLabs']]],
  ['charting',['Charting',['../namespace_x_labs_1_1_forms_1_1_charting.html',1,'XLabs::Forms']]],
  ['controls',['Controls',['../namespace_x_labs_1_1_forms_1_1_charting_1_1_controls.html',1,'XLabs::Forms::Charting']]],
  ['controls',['Controls',['../namespace_x_labs_1_1_forms_1_1_controls.html',1,'XLabs::Forms']]],
  ['converter',['Converter',['../namespace_x_labs_1_1_forms_1_1_converter.html',1,'XLabs::Forms']]],
  ['cryptography',['Cryptography',['../namespace_x_labs_1_1_cryptography.html',1,'XLabs']]],
  ['data',['Data',['../namespace_x_labs_1_1_data.html',1,'XLabs']]],
  ['device',['Device',['../namespace_x_labs_1_1_platform_1_1_device.html',1,'XLabs::Platform']]],
  ['email',['Email',['../namespace_x_labs_1_1_platform_1_1_services_1_1_email.html',1,'XLabs::Platform::Services']]],
  ['enums',['Enums',['../namespace_x_labs_1_1_enums.html',1,'XLabs']]],
  ['events',['Events',['../namespace_x_labs_1_1_forms_1_1_charting_1_1_events.html',1,'XLabs::Forms::Charting']]],
  ['exceptions',['Exceptions',['../namespace_x_labs_1_1_forms_1_1_exceptions.html',1,'XLabs::Forms']]],
  ['exceptions',['Exceptions',['../namespace_x_labs_1_1_exceptions.html',1,'XLabs']]],
  ['extensions',['Extensions',['../namespace_x_labs_1_1_forms_1_1_extensions.html',1,'XLabs::Forms']]],
  ['extensions',['Extensions',['../namespace_x_labs_1_1_extensions.html',1,'XLabs']]],
  ['extensions',['Extensions',['../namespace_x_labs_1_1_platform_1_1_extensions.html',1,'XLabs::Platform']]],
  ['forms',['Forms',['../namespace_x_labs_1_1_forms.html',1,'XLabs']]],
  ['geolocation',['Geolocation',['../namespace_x_labs_1_1_platform_1_1_services_1_1_geolocation.html',1,'XLabs::Platform::Services']]],
  ['helpers',['Helpers',['../namespace_x_labs_1_1_settings_1_1_xam_settings_1_1_helpers.html',1,'XLabs::Settings::XamSettings']]],
  ['io',['IO',['../namespace_x_labs_1_1_platform_1_1_services_1_1_i_o.html',1,'XLabs::Platform::Services']]],
  ['ioc',['Ioc',['../namespace_x_labs_1_1_ioc.html',1,'XLabs']]],
  ['jsonnet',['JsonNET',['../namespace_x_labs_1_1_serialization_1_1_json_n_e_t.html',1,'XLabs::Serialization']]],
  ['media',['Media',['../namespace_x_labs_1_1_platform_1_1_services_1_1_media.html',1,'XLabs::Platform::Services']]],
  ['monodroid',['MonoDroid',['../namespace_x_labs_1_1_forms_1_1_controls_1_1_mono_droid.html',1,'XLabs::Forms::Controls']]],
  ['mvvm',['Mvvm',['../namespace_x_labs_1_1_forms_1_1_mvvm.html',1,'XLabs::Forms']]],
  ['mvvm',['Mvvm',['../namespace_x_labs_1_1_platform_1_1_mvvm.html',1,'XLabs::Platform']]],
  ['ninject',['Ninject',['../namespace_x_labs_1_1_ioc_1_1_ninject.html',1,'XLabs::Ioc']]],
  ['pages',['Pages',['../namespace_x_labs_1_1_forms_1_1_pages.html',1,'XLabs::Forms']]],
  ['platform',['Platform',['../namespace_x_labs_1_1_platform.html',1,'XLabs']]],
  ['protobuf',['ProtoBuf',['../namespace_x_labs_1_1_serialization_1_1_proto_buf.html',1,'XLabs::Serialization']]],
  ['reporting',['Reporting',['../namespace_x_labs_1_1_reporting.html',1,'XLabs']]],
  ['restclient',['RestClient',['../namespace_x_labs_1_1_web_1_1_rest_client.html',1,'XLabs::Web']]],
  ['sensorbar',['SensorBar',['../namespace_x_labs_1_1_forms_1_1_controls_1_1_sensor_bar.html',1,'XLabs::Forms::Controls']]],
  ['serialization',['Serialization',['../namespace_x_labs_1_1_serialization.html',1,'XLabs']]],
  ['services',['Services',['../namespace_x_labs_1_1_forms_1_1_services.html',1,'XLabs::Forms']]],
  ['services',['Services',['../namespace_x_labs_1_1_platform_1_1_services.html',1,'XLabs::Platform']]],
  ['settings',['Settings',['../namespace_x_labs_1_1_settings.html',1,'XLabs']]],
  ['simpleinjectorcontainer',['SimpleInjectorContainer',['../namespace_x_labs_1_1_ioc_1_1_simple_injector_container.html',1,'XLabs::Ioc']]],
  ['sqlite',['SQLite',['../namespace_x_labs_1_1_caching_1_1_s_q_lite.html',1,'XLabs::Caching']]],
  ['systemtextjson',['SystemTextJson',['../namespace_x_labs_1_1_serialization_1_1_system_text_json.html',1,'XLabs::Serialization']]],
  ['timessquare',['TimesSquare',['../namespace_x_labs_1_1_forms_1_1_controls_1_1_mono_droid_1_1_times_square.html',1,'XLabs::Forms::Controls::MonoDroid']]],
  ['tinyioc',['TinyIOC',['../namespace_x_labs_1_1_ioc_1_1_tiny_i_o_c.html',1,'XLabs::Ioc']]],
  ['unity',['Unity',['../namespace_x_labs_1_1_ioc_1_1_unity.html',1,'XLabs::Ioc']]],
  ['utilities',['Utilities',['../namespace_x_labs_1_1_utilities.html',1,'XLabs']]],
  ['validation',['Validation',['../namespace_x_labs_1_1_forms_1_1_validation.html',1,'XLabs::Forms']]],
  ['web',['Web',['../namespace_x_labs_1_1_web.html',1,'XLabs']]],
  ['winrt',['WinRT',['../namespace_x_labs_1_1_platform_1_1_win_r_t.html',1,'XLabs::Platform']]],
  ['x',['X',['../class_x_labs_1_1_forms_1_1_charting_1_1_events_1_1_pie_drawing_data.html#acb5303bbd6eaf8873953c63e8188ad36',1,'XLabs.Forms.Charting.Events.PieDrawingData.X()'],['../class_x_labs_1_1_forms_1_1_charting_1_1_events_1_1_single_drawing_data.html#a2e8520c9dc81fead8bcd8e02f94e0687',1,'XLabs.Forms.Charting.Events.SingleDrawingData.X()'],['../class_x_labs_1_1_forms_1_1_charting_1_1_events_1_1_text_drawing_data.html#a18c6b33db2d8215e46f2f5a72a3cd41c',1,'XLabs.Forms.Charting.Events.TextDrawingData.X()'],['../class_x_labs_1_1_vector3.html#a0e64c3d9f96793a764e10efcd11632f9',1,'XLabs.Vector3.X()']]],
  ['xalign',['XAlign',['../class_x_labs_1_1_forms_1_1_controls_1_1_extended_entry.html#a3da31074188b14243aabfb2616c02330',1,'XLabs::Forms::Controls::ExtendedEntry']]],
  ['xalignproperty',['XAlignProperty',['../class_x_labs_1_1_forms_1_1_controls_1_1_extended_entry.html#ac1f4c514d68c5fbb954075998105e89d',1,'XLabs::Forms::Controls::ExtendedEntry']]],
  ['xamarin',['Xamarin',['../class_x_labs_1_1_forms_1_1_controls_1_1_hybrid_web_view_renderer_1_1_xamarin.html#a85fa0a8d9bf92b042e44812d0c6e49bb',1,'XLabs::Forms::Controls::HybridWebViewRenderer::Xamarin']]],
  ['xamarin',['Xamarin',['../class_x_labs_1_1_forms_1_1_controls_1_1_hybrid_web_view_renderer_1_1_xamarin.html',1,'XLabs::Forms::Controls::HybridWebViewRenderer']]],
  ['xamsettings',['XamSettings',['../namespace_x_labs_1_1_settings_1_1_xam_settings.html',1,'XLabs::Settings']]],
  ['xamsettingsconfigsettings',['XamSettingsConfigSettings',['../class_x_labs_1_1_settings_1_1_xam_settings_1_1_xam_settings_config_settings.html',1,'XLabs::Settings::XamSettings']]],
  ['xamsettingsconfigsettings_2ecs',['XamSettingsConfigSettings.cs',['../_xam_settings_config_settings_8cs.html',1,'']]],
  ['xdpi',['Xdpi',['../interface_x_labs_1_1_platform_1_1_device_1_1_i_display.html#a9208f3fecc245c9b3a153a5566bc3cdf',1,'XLabs.Platform.Device.IDisplay.Xdpi()'],['../class_x_labs_1_1_platform_1_1_device_1_1_display.html#aa766546a5305df9d15b0f81f7ef92c82',1,'XLabs.Platform.Device.Display.Xdpi()']]],
  ['xformsapp',['XFormsApp',['../class_x_labs_1_1_platform_1_1_mvvm_1_1_x_forms_app.html#abef65b4e941da3df90466fafa6500a59',1,'XLabs.Platform.Mvvm.XFormsApp.XFormsApp()'],['../class_x_labs_1_1_platform_1_1_mvvm_1_1_x_forms_app.html#ac6523eaf7e5b22eec3c424493a661aff',1,'XLabs.Platform.Mvvm.XFormsApp.XFormsApp(TApp context)']]],
  ['xformsapp',['XFormsApp',['../class_x_labs_1_1_platform_1_1_mvvm_1_1_x_forms_app.html',1,'XLabs::Platform::Mvvm']]],
  ['xformsapp_2ecs',['XFormsApp.cs',['../_forms_2_x_labs_8_forms_8i_o_s_2_x_forms_app_8cs.html',1,'']]],
  ['xformsapp_2ecs',['XFormsApp.cs',['../_forms_2_x_labs_8_forms_8_win_universal_2_x_forms_app_8cs.html',1,'']]],
  ['xformsapp_2ecs',['XFormsApp.cs',['../_forms_2_x_labs_8_forms_8_w_p8_2_x_forms_app_8cs.html',1,'']]],
  ['xformsapp_2ecs',['XFormsApp.cs',['../_platform_2_x_labs_8_platform_2_mvvm_2_x_forms_app_8cs.html',1,'']]],
  ['xformsapp_2ecs',['XFormsApp.cs',['../_forms_2_x_labs_8_forms_8_droid_2_x_forms_app_8cs.html',1,'']]],
  ['xformsapp_3c_20application_20_3e',['XFormsApp&lt; Application &gt;',['../class_x_labs_1_1_platform_1_1_mvvm_1_1_x_forms_app.html',1,'XLabs::Platform::Mvvm']]],
  ['xformsapp_3c_20xformsapplicationdelegate_20_3e',['XFormsApp&lt; XFormsApplicationDelegate &gt;',['../class_x_labs_1_1_platform_1_1_mvvm_1_1_x_forms_app.html',1,'XLabs::Platform::Mvvm']]],
  ['xformsapp_3c_20xformsapplicationdroid_20_3e',['XFormsApp&lt; XFormsApplicationDroid &gt;',['../class_x_labs_1_1_platform_1_1_mvvm_1_1_x_forms_app.html',1,'XLabs::Platform::Mvvm']]],
  ['xformsappdroid',['XFormsAppDroid',['../class_x_labs_1_1_forms_1_1_x_forms_app_droid.html',1,'XLabs::Forms']]],
  ['xformsappdroid',['XFormsAppDroid',['../class_x_labs_1_1_forms_1_1_x_forms_app_droid.html#a97374017e7a7ecf969fbca9d87bff5fe',1,'XLabs.Forms.XFormsAppDroid.XFormsAppDroid()'],['../class_x_labs_1_1_forms_1_1_x_forms_app_droid.html#a6687fae3cf14f9ab8448da571f1b2f9f',1,'XLabs.Forms.XFormsAppDroid.XFormsAppDroid(XFormsApplicationDroid app)']]],
  ['xformsappios',['XFormsAppiOS',['../class_x_labs_1_1_forms_1_1_x_forms_appi_o_s.html',1,'XLabs::Forms']]],
  ['xformsappios',['XFormsAppiOS',['../class_x_labs_1_1_forms_1_1_x_forms_appi_o_s.html#a71e097e833740727d11863f3385cf548',1,'XLabs.Forms.XFormsAppiOS.XFormsAppiOS()'],['../class_x_labs_1_1_forms_1_1_x_forms_appi_o_s.html#af0d22a0a3cb4dbfc00cf559b4d207428',1,'XLabs.Forms.XFormsAppiOS.XFormsAppiOS(XFormsApplicationDelegate appDelegate)']]],
  ['xformsapplicationdelegate',['XFormsApplicationDelegate',['../class_x_labs_1_1_forms_1_1_x_forms_application_delegate.html',1,'XLabs::Forms']]],
  ['xformsapplicationdroid',['XFormsApplicationDroid',['../class_x_labs_1_1_forms_1_1_x_forms_application_droid.html',1,'XLabs::Forms']]],
  ['xformsappwin',['XFormsAppWin',['../class_x_labs_1_1_forms_1_1_x_forms_app_win.html',1,'XLabs::Forms']]],
  ['xformsappwin',['XFormsAppWin',['../class_x_labs_1_1_forms_1_1_x_forms_app_win.html#a6a02418a902b34b3878209bae494f896',1,'XLabs.Forms.XFormsAppWin.XFormsAppWin()'],['../class_x_labs_1_1_forms_1_1_x_forms_app_win.html#a088e5820a3bd5306fcd04923a4214e98',1,'XLabs.Forms.XFormsAppWin.XFormsAppWin(Application application)']]],
  ['xformsappwp',['XFormsAppWP',['../class_x_labs_1_1_forms_1_1_x_forms_app_w_p.html',1,'XLabs::Forms']]],
  ['xformsappwp',['XFormsAppWP',['../class_x_labs_1_1_forms_1_1_x_forms_app_w_p.html#addfac5a62cecc0d8ae5ef5f68387b7c2',1,'XLabs.Forms.XFormsAppWP.XFormsAppWP()'],['../class_x_labs_1_1_forms_1_1_x_forms_app_w_p.html#a3b5a895cee84a9a3841fd7f9842542fc',1,'XLabs.Forms.XFormsAppWP.XFormsAppWP(Application application)']]],
  ['xfrom',['XFrom',['../class_x_labs_1_1_forms_1_1_charting_1_1_events_1_1_double_drawing_data.html#a8ab69dd1e789a4667126701fc59a615a',1,'XLabs::Forms::Charting::Events::DoubleDrawingData']]],
  ['xlabs',['XLabs',['../namespace_x_labs.html',1,'']]],
  ['xml',['Xml',['../namespace_x_labs_1_1_serialization.html#aa1c67d4e660d4f1decffd5f6f85b597ea9ec8e4e3ab4c7eeba097f27d7364d743',1,'XLabs::Serialization']]],
  ['xmlserializer_2ecs',['XmlSerializer.cs',['../_xml_serializer_8cs.html',1,'']]],
  ['xnamicrophone',['XnaMicrophone',['../class_x_labs_1_1_platform_1_1_services_1_1_media_1_1_xna_microphone.html#af96ecac99d0c8e8d37d9259f2f39bcb8',1,'XLabs::Platform::Services::Media::XnaMicrophone']]],
  ['xnamicrophone',['XnaMicrophone',['../class_x_labs_1_1_platform_1_1_services_1_1_media_1_1_xna_microphone.html',1,'XLabs::Platform::Services::Media']]],
  ['xnamicrophone_2ecs',['XnaMicrophone.cs',['../_xna_microphone_8cs.html',1,'']]],
  ['xpath',['XPath',['../class_x_labs_1_1_forms_1_1_charting_1_1_controls_1_1_chart.html#a3bd0d97b2b944f53bb91338f47da9915',1,'XLabs::Forms::Charting::Controls::Chart']]],
  ['xpathproperty',['XPathProperty',['../class_x_labs_1_1_forms_1_1_charting_1_1_controls_1_1_chart.html#a8ae72a9b5b28b1bf7b31903da78cfa93',1,'XLabs::Forms::Charting::Controls::Chart']]],
  ['xto',['XTo',['../class_x_labs_1_1_forms_1_1_charting_1_1_events_1_1_double_drawing_data.html#afab08a3529035d5e659659c9b22fcb11',1,'XLabs::Forms::Charting::Events::DoubleDrawingData']]]
];
