var searchData=
[
  ['genericconfigsettingsmgr',['GenericConfigSettingsMgr',['../class_x_labs_1_1_settings_1_1_generic_config_settings_mgr.html',1,'XLabs::Settings']]],
  ['geolocationexception',['GeolocationException',['../class_x_labs_1_1_platform_1_1_services_1_1_geolocation_1_1_geolocation_exception.html',1,'XLabs::Platform::Services::Geolocation']]],
  ['geolocator',['Geolocator',['../class_x_labs_1_1_platform_1_1_services_1_1_geolocation_1_1_geolocator.html',1,'XLabs::Platform::Services::Geolocation']]],
  ['gesturecollection',['GestureCollection',['../class_x_labs_1_1_forms_1_1_behaviors_1_1_gesture_collection.html',1,'XLabs::Forms::Behaviors']]],
  ['gestureinterest',['GestureInterest',['../class_x_labs_1_1_forms_1_1_behaviors_1_1_gesture_interest.html',1,'XLabs::Forms::Behaviors']]],
  ['gestureresult',['GestureResult',['../class_x_labs_1_1_forms_1_1_behaviors_1_1_gesture_result.html',1,'XLabs::Forms::Behaviors']]],
  ['gestures',['Gestures',['../class_x_labs_1_1_forms_1_1_behaviors_1_1_gestures.html',1,'XLabs::Forms::Behaviors']]],
  ['gesturescontentview',['GesturesContentView',['../class_x_labs_1_1_forms_1_1_controls_1_1_gestures_content_view.html',1,'XLabs::Forms::Controls']]],
  ['gesturescontentviewrenderer',['GesturesContentViewRenderer',['../class_x_labs_1_1_forms_1_1_controls_1_1_gestures_content_view_renderer.html',1,'XLabs::Forms::Controls']]],
  ['gridcollectionview',['GridCollectionView',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_collection_view.html',1,'XLabs::Forms::Controls']]],
  ['griddatasource',['GridDataSource',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_data_source.html',1,'XLabs::Forms::Controls']]],
  ['griditemselectedviewoverlay',['GridItemSelectedViewOverlay',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_item_selected_view_overlay.html',1,'XLabs::Forms::Controls']]],
  ['gridlayout',['GridLayout',['../class_x_labs_1_1_forms_1_1_behaviors_1_1_grid_layout.html',1,'XLabs::Forms::Behaviors']]],
  ['gridview',['GridView',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_view.html',1,'XLabs::Forms::Controls']]],
  ['gridviewcell',['GridViewCell',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_view_cell.html',1,'XLabs::Forms::Controls']]],
  ['gridviewcellrenderer',['GridViewCellRenderer',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_view_cell_renderer.html',1,'XLabs::Forms::Controls']]],
  ['gridviewdelegate',['GridViewDelegate',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_view_delegate.html',1,'XLabs::Forms::Controls']]],
  ['gridviewrenderer',['GridViewRenderer',['../class_x_labs_1_1_forms_1_1_controls_1_1_grid_view_renderer.html',1,'XLabs::Forms::Controls']]],
  ['gyroscope',['Gyroscope',['../class_x_labs_1_1_platform_1_1_device_1_1_gyroscope.html',1,'XLabs::Platform::Device']]]
];
