var dir_e3958eea36bee96ba0bc7e746939ead7 =
[
    [ "GesturesContentViewRenderer.cs", "_x_labs_8_forms_8_droid_2_controls_2_gestures_content_view_2_gestures_content_view_renderer_8cs.html", "_x_labs_8_forms_8_droid_2_controls_2_gestures_content_view_2_gestures_content_view_renderer_8cs" ]
];