var namespace_x_labs_1_1_platform_1_1_device =
[
    [ "Accelerometer", "class_x_labs_1_1_platform_1_1_device_1_1_accelerometer.html", "class_x_labs_1_1_platform_1_1_device_1_1_accelerometer" ],
    [ "AndroidBluetoothDevice", "class_x_labs_1_1_platform_1_1_device_1_1_android_bluetooth_device.html", "class_x_labs_1_1_platform_1_1_device_1_1_android_bluetooth_device" ],
    [ "AndroidDevice", "class_x_labs_1_1_platform_1_1_device_1_1_android_device.html", "class_x_labs_1_1_platform_1_1_device_1_1_android_device" ],
    [ "AppleDevice", "class_x_labs_1_1_platform_1_1_device_1_1_apple_device.html", "class_x_labs_1_1_platform_1_1_device_1_1_apple_device" ],
    [ "Battery", "class_x_labs_1_1_platform_1_1_device_1_1_battery.html", "class_x_labs_1_1_platform_1_1_device_1_1_battery" ],
    [ "BluetoothDevice", "class_x_labs_1_1_platform_1_1_device_1_1_bluetooth_device.html", "class_x_labs_1_1_platform_1_1_device_1_1_bluetooth_device" ],
    [ "BluetoothHub", "class_x_labs_1_1_platform_1_1_device_1_1_bluetooth_hub.html", "class_x_labs_1_1_platform_1_1_device_1_1_bluetooth_hub" ],
    [ "BroadcastMonitor", "class_x_labs_1_1_platform_1_1_device_1_1_broadcast_monitor.html", "class_x_labs_1_1_platform_1_1_device_1_1_broadcast_monitor" ],
    [ "DeviceInfo", "class_x_labs_1_1_platform_1_1_device_1_1_device_info.html", "class_x_labs_1_1_platform_1_1_device_1_1_device_info" ],
    [ "DeviceSensor", "class_x_labs_1_1_platform_1_1_device_1_1_device_sensor.html", "class_x_labs_1_1_platform_1_1_device_1_1_device_sensor" ],
    [ "Display", "class_x_labs_1_1_platform_1_1_device_1_1_display.html", "class_x_labs_1_1_platform_1_1_device_1_1_display" ],
    [ "Gyroscope", "class_x_labs_1_1_platform_1_1_device_1_1_gyroscope.html", "class_x_labs_1_1_platform_1_1_device_1_1_gyroscope" ],
    [ "IAccelerometer", "interface_x_labs_1_1_platform_1_1_device_1_1_i_accelerometer.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_accelerometer" ],
    [ "IBattery", "interface_x_labs_1_1_platform_1_1_device_1_1_i_battery.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_battery" ],
    [ "IBluetoothDevice", "interface_x_labs_1_1_platform_1_1_device_1_1_i_bluetooth_device.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_bluetooth_device" ],
    [ "IBluetoothHub", "interface_x_labs_1_1_platform_1_1_device_1_1_i_bluetooth_hub.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_bluetooth_hub" ],
    [ "IDevice", "interface_x_labs_1_1_platform_1_1_device_1_1_i_device.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_device" ],
    [ "IDisplay", "interface_x_labs_1_1_platform_1_1_device_1_1_i_display.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_display" ],
    [ "IGyroscope", "interface_x_labs_1_1_platform_1_1_device_1_1_i_gyroscope.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_gyroscope" ],
    [ "ISensor", "interface_x_labs_1_1_platform_1_1_device_1_1_i_sensor.html", "interface_x_labs_1_1_platform_1_1_device_1_1_i_sensor" ],
    [ "Pad", "class_x_labs_1_1_platform_1_1_device_1_1_pad.html", "class_x_labs_1_1_platform_1_1_device_1_1_pad" ],
    [ "Phone", "class_x_labs_1_1_platform_1_1_device_1_1_phone.html", "class_x_labs_1_1_platform_1_1_device_1_1_phone" ],
    [ "Pod", "class_x_labs_1_1_platform_1_1_device_1_1_pod.html", "class_x_labs_1_1_platform_1_1_device_1_1_pod" ],
    [ "Simulator", "class_x_labs_1_1_platform_1_1_device_1_1_simulator.html", null ],
    [ "WindowsPhoneDevice", "class_x_labs_1_1_platform_1_1_device_1_1_windows_phone_device.html", "class_x_labs_1_1_platform_1_1_device_1_1_windows_phone_device" ],
    [ "Wp81Device", "class_x_labs_1_1_platform_1_1_device_1_1_wp81_device.html", "class_x_labs_1_1_platform_1_1_device_1_1_wp81_device" ]
];